baseURL = "https://nvflt.github.io"
languageCode = "en-us"
title = "Winter is coming"
theme = "ananke"
<<<<<<< Updated upstream
publishDir = "docs"
=======
##publishDir = "docs"
>>>>>>> Stashed changes
